(load "../../src/tests-driver.scm")
(load "../../src/tests-1.1-req.scm")
(define (emit-program x)
 (unless (integer? x) (raise 'not-an-integer))
 (emit "     .text")
 (emit "     .intel_syntax noprefix")
 (emit "     .globl _scheme_entry")
 (emit "_scheme_entry:")
 (emit "    mov eax, ~s" x)
 (emit "    ret"))
